# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Robbie Netzorg
#tagline:             ''
description: >
        A Computer Science student at Columbia University who, like all other ambitious students, started a blog. These
        are thoughts that aren't supposed to be taken seriously
url:                 http://robbienetz.org
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Robbie Netzorg
  #url:               https://twitter.com/mdo
  email:             rgn2112@columbia.edu

# Custom vars
version:             1.0.0

# plugins
plugins: [jekyll-paginate]

collections:
  projects:
    output: true
    permalink: localhost:4000/:path/